### ISSUE TITLE
Support for Llama3 / Ollama supported LLMs

### ISSUE THREAD

**Issue by t3chn0m4g3** [mariocandela/beelzebub#114]
**Is your feature request related to a problem? Please describe.**
Using OpenAI API can involve unforeseen costs.

**Describe the solution you'd like**
Adding support for Llama3 / Ollama supported LLMs could allow for streamlining invests and for larger installations.

**Comment by mariocandela** [comment]
Hi @t3chn0m4g3,

Nice to meet you! 

Thanks for your contribution, I will take charge of this new feature in the following days :)

Cheers 

Mario

**Comment by t3chn0m4g3** [comment]
@t3chn0m4g3 Likewise, this is great news! Looking forward to it!

**Comment by mariocandela** [comment]
Hi @t3chn0m4g3,

Download the latest version and take a look here: https://github.com/mariocandela/beelzebub/issues/114

Happy hacking ❤️ 

Cheers

Mario

**Comment by t3chn0m4g3** [comment]
@mariocandela Closing this is fine, thank you very much for taking this with warp speed 🤩🚀

I can now start testing, if everything works out I will be happy to integrate this into T-Pot.

Thanks again ❤️

**Comment by t3chn0m4g3** [comment]
Getting [started](https://github.com/telekom-security/tpotce/discussions/1629) 👋

**Comment by mariocandela** [comment]
@t3chn0m4g3 if I can help you in any way, write to me I am happy to help you 😊

**Comment by t3chn0m4g3** [comment]
@mariocandela Thank you, highly appreciated 😍

**Comment by t3chn0m4g3** [comment]
Lab is set up, now getting to work :)

**Comment by t3chn0m4g3** [comment]
@mariocandela - In `plugins/llm-integration.go` I can see the ollama endpoint as a const ...
https://github.com/mariocandela/beelzebub/blob/628e20e01fef2b0ad2261fe84ae6b0cc10d64823/plugins/llm-integration.go#L13-L18
... is there any option in the config or the cli to overwrite the endpoint with a different host (assuming that ollama will probably not reside on the honeypot)?

**Comment by t3chn0m4g3** [comment]
@mariocandela  Reading helps... sorry...
```
apiVersion: "v1"
protocol: "ssh"
address: ":2222"
description: "SSH Ollama Llama3"
commands:
  - regex: "^(.+)$"
    plugin: "LLMHoneypot"
serverVersion: "OpenSSH"
serverName: "ubuntu"
passwordRegex: "^(root|qwerty|Smoker666|123456|jenkins|minecraft|sinus|alex|postgres|Ly123456)$"
deadlineTimeoutSeconds: 60
plugin:
   llmModel: "llama3"
   host: "http://example.com/api/chat" #default http://localhost:11434/api/chat
```
