### ISSUE TITLE
Error ExecuteModel

### ISSUE THREAD

**Issue by domingo13** [mariocandela/beelzebub#161]
**Describe the bug**
All attempts to use gpt4-o with ssh ends with:
beelzebub  | {"level":"error","msg":"Error ExecuteModel: "whatever command I try", no choices"}

**To Reproduce**
1. I insert my OpenAI API key in the service yaml file
2. Run docker compose up
3. SSH into the port, login and run ls
4. Get: "beelzebub  | {"level":"error","msg":"Error ExecuteModel: ls, no choices"}"

Here is my docker-compose.yml:
```
services:
  beelzebub:
    #network_mode: host # Not work on Mac OS
    container_name: beelzebub
    image: m4r10/beelzebub:v3.3.3
    restart: always
    ports: # Remove me, if you use configuration network_mode: host
      - "8080:8080"
      - "2222:2222"
      - "3306:3306"
      - "5432:5432"
    volumes:
      - "./configurations:/configurations"

```
Output from console:
```
root@honeypot:~/beelzebub-example# docker compose up
WARN[0000] /root/beelzebub-example/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 1/0
 ✔ Container beelzebub  Created                                                                                                                                                                               0.0s 
Attaching to beelzebub
beelzebub  | 
beelzebub  | ██████  ███████ ███████ ██      ███████ ███████ ██████  ██    ██ ██████  
beelzebub  | ██   ██ ██      ██      ██         ███  ██      ██   ██ ██    ██ ██   ██ 
beelzebub  | ██████  █████   █████   ██        ███   █████   ██████  ██    ██ ██████  
beelzebub  | ██   ██ ██      ██      ██       ███    ██      ██   ██ ██    ██ ██   ██ 
beelzebub  | ██████  ███████ ███████ ███████ ███████ ███████ ██████   ██████  ██████  
beelzebub  | Honeypot Framework, happy hacking!
beelzebub  | {"commands":3,"level":"info","msg":"Init service: Wordpress 6.0, PHP 7.4.29, Apache 2.4.53","port":":80"}
beelzebub  | {"commands":1,"level":"info","msg":"Init service: Apache 401","port":":8080"}
beelzebub  | {"commands":9,"level":"info","msg":"GetInstance service ssh","port":":22"}
beelzebub  | {"commands":1,"level":"info","msg":"GetInstance service ssh","port":":2222"}
beelzebub  | {"banner":"8.0.29","level":"info","msg":"Init service tcp","port":":3306"}
beelzebub  | {"banner":"9.6.0","level":"info","msg":"Init service tcp","port":":5432"}
beelzebub  | {"event":{"DateTime":"2025-02-16T10:45:27Z","RemoteAddr":"172.16.1.196:37716","Protocol":"SSH","Command":"","CommandOutput":"","Status":"Stateless","Msg":"New SSH attempt","ID":"8e39251f-2428-4707-8732-8dc736ff8110","Environ":"","User":"root","Password":"root","Client":"SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.5","Headers":"","Cookies":"","UserAgent":"","HostHTTPRequest":"","Body":"","HTTPMethod":"","RequestURI":"","Description":"SSH interactive ChatGPT","SourceIp":"172.16.1.196","SourcePort":"37716","TLSServerName":""},"level":"info","msg":"New Event","status":"Stateless"}
beelzebub  | {"event":{"DateTime":"2025-02-16T10:45:27Z","RemoteAddr":"172.16.1.196:37716","Protocol":"SSH","Command":"","CommandOutput":"","Status":"Start","Msg":"New SSH Session","ID":"c0faf3d1-dd95-4e61-9bcc-dda8d6d8dc49","Environ":"LANG=en_US.UTF-8","User":"root","Password":"","Client":"","Headers":"","Cookies":"","UserAgent":"","HostHTTPRequest":"","Body":"","HTTPMethod":"","RequestURI":"","Description":"SSH interactive ChatGPT","SourceIp":"172.16.1.196","SourcePort":"37716","TLSServerName":""},"level":"info","msg":"New Event","status":"Start"}
beelzebub  | {"level":"error","msg":"Error ExecuteModel: ls, no choices"}
beelzebub  | {"event":{"DateTime":"2025-02-16T10:45:31Z","RemoteAddr":"172.16.1.196:37716","Protocol":"SSH","Command":"ls","CommandOutput":"command not found","Status":"Interaction","Msg":"New SSH Terminal Session","ID":"c0faf3d1-dd95-4e61-9bcc-dda8d6d8dc49","Environ":"","User":"","Password":"","Client":"","Headers":"","Cookies":"","UserAgent":"","HostHTTPRequest":"","Body":"","HTTPMethod":"","RequestURI":"","Description":"SSH interactive ChatGPT","SourceIp":"172.16.1.196","SourcePort":"37716","TLSServerName":""},"level":"info","msg":"New Event","status":"Interaction"}
beelzebub  | {"level":"error","msg":"Error ExecuteModel: dir, no choices"}
beelzebub  | {"event":{"DateTime":"2025-02-16T10:45:37Z","RemoteAddr":"172.16.1.196:37716","Protocol":"SSH","Command":"dir","CommandOutput":"command not found","Status":"Interaction","Msg":"New SSH Terminal Session","ID":"c0faf3d1-dd95-4e61-9bcc-dda8d6d8dc49","Environ":"","User":"","Password":"","Client":"","Headers":"","Cookies":"","UserAgent":"","HostHTTPRequest":"","Body":"","HTTPMethod":"","RequestURI":"","Description":"SSH interactive ChatGPT","SourceIp":"172.16.1.196","SourcePort":"37716","TLSServerName":""},"level":"info","msg":"New Event","status":"Interaction"}
beelzebub  | {"event":{"DateTime":"2025-02-16T10:45:40Z","RemoteAddr":"","Protocol":"","Command":"","CommandOutput":"","Status":"End","Msg":"End SSH Session","ID":"c0faf3d1-dd95-4e61-9bcc-dda8d6d8dc49","Environ":"","User":"","Password":"","Client":"","Headers":"","Cookies":"","UserAgent":"","HostHTTPRequest":"","Body":"","HTTPMethod":"","RequestURI":"","Description":"","SourceIp":"","SourcePort":"","TLSServerName":""},"level":"info","msg":"New Event","status":"End"}
```

configurations/services/ssh-2222.yaml:
```
apiVersion: "v1"
protocol: "ssh"
address: ":2222"
description: "SSH interactive ChatGPT"
commands:
  - regex: "^(.+)$"
    plugin: "LLMHoneypot"
serverVersion: "OpenSSH"
serverName: "ubuntu"
passwordRegex: "^(root|qwerty|Smoker666|123456|jenkins|minecraft|sinus|alex|postgres|Ly123456)$"
deadlineTimeoutSeconds: 120
plugin:
    llmModel: "gpt4-o"
    openAISecretKey: "sk-xxx"
```
