### ISSUE TITLE
Bug: Inline SSH honeypot command not working

### ISSUE THREAD

**Issue by domingo13** [mariocandela/beelzebub#166]
**Describe the bug**
Inline SSH honeypot command not working

**To Reproduce**
ssh root@examplecom "ls"
root@example.com's password: 
command not found

**Expected behavior**
Execute the inline command and interact with GPT

**Logs**
beelzebub  | {"event":{"DateTime":"2025-02-20T16:58:04Z","RemoteAddr":"45.91.193.32:51444","Protocol":"SSH","Command":"uname -r | awk '{printf $1}'","CommandOutput":"command not found","Status":"Start","Msg":"New SSH Session","ID":"7137f694-4aa1-4aa3-86c5-92737e5cac9c","Environ":"","User":"demo","Password":"","Client":"","Headers":"","Cookies":"","UserAgent":"","HostHTTPRequest":"","Body":"","HTTPMethod":"","RequestURI":"","Description":"SSH interactive OpenAI  GPT-4","SourceIp":"45.91.193.32","SourcePort":"51444","TLSServerName":""},"level":"info","msg":"New Event","status":"Start","time":"2025-02-20T16:58:04Z"}

**Additional context**
Looks like a repeat of #129 

Using:
 image: m4r10/beelzebub:v3.3.5

**Comment by mariocandela** [comment]
Hi Mate, 

I hope you are well.

So I think the problem is a typo into SSH honeypot: https://github.com/mariocandela/beelzebub/blob/main/configurations/services/ssh-2222.yaml#L14

Check your OpenAI model name 😄 

ps: I just fixed the typo into the docs, thanks you! 

Thanks for your time 

Cheers 

Mario

**Comment by domingo13** [comment]
Hello there :-)

If I do an interactive login it works just fine:
beelzebub  | {"event":{"DateTime":"2025-02-20T18:45:36Z","RemoteAddr":"172.30.255.196:41706","Protocol":"SSH","Command":"ls","CommandOutput":"Documents  \nDownloads  \nMusic  \nPictures  \nVideos  \nDesktop  ","Status":"Interaction","Msg":"New SSH Terminal Session","ID":"037300aa-e056-4960-922c-42e330ff9875","Environ":"","User":"","Password":"","Client":"","Headers":"","Cookies":"","UserAgent":"","HostHTTPRequest":"","Body":"","HTTPMethod":"","RequestURI":"","Description":"SSH interactive OpenAI  GPT-4","SourceIp":"172.30.255.196","SourcePort":"41706","TLSServerName":""},"level":"info","msg":"New Event","status":"Interaction","time":"2025-02-20T18:45:36Z"}

**Comment by domingo13** [comment]
This is my service configuration:
```

apiVersion: "v1"
protocol: "ssh"
address: ":2222"
description: "SSH interactive OpenAI  GPT-4"
commands:
  - regex: "^(.+)$"
    plugin: "LLMHoneypot"
serverVersion: "OpenSSH"
serverName: "ubuntu"
passwordRegex: "^(root|qwerty|Smoker666|123456|jenkins|minecraft|sinus|alex|postgres|Ly123456|password|oracle|admin)$"
deadlineTimeoutSeconds: 60
plugin:
   llmProvider: "openai"
   llmModel: "gpt-4o-mini" #Models https://platform.openai.com/docs/models
   openAISecretKey: "sk-xxx"

```
