### ISSUE TITLE
Fail to load if compose volumes are not relative

### ISSUE THREAD

**Issue by domingo13** [mariocandela/beelzebub#167]
**Describe the bug**
If I use direct refences in docker-compose.yml Beezlebub fails to load due to using relative references in the application.

**To Reproduce**
Setup docker-compose.yml like this:
```
services:
  beelzebub:
    #network_mode: host # Not work on Mac OS
    container_name: beelzebub
    image: m4r10/beelzebub:v3.3.5
    restart: always
    ports: # Remove me, if you use configuration network_mode: host
      # - "22:22"
      #- "8080:8080"
      - "2222:2222"
        #- "3306:3306"
        # - "80:80"
        #- "5432:5432"
    volumes:
      - /opt/beelzebub/configurations/:/configurations/"
      - /opt/beelzebub/logs:/logs
      
```
**Logs**
```
docker compose up
[+] Running 2/2
 ✔ Network beelzebub_default  Created                                                                                                                                                                         0.1s 
 ✔ Container beelzebub        Created                                                                                                                                                                         0.0s 
Attaching to beelzebub
beelzebub  | time="2025-02-20T19:08:40Z" level=fatal msg="Error during ReadConfigurationsCore: : in file ./configurations/beelzebub.yaml: open ./configurations/beelzebub.yaml: no such file or directory"
beelzebub exited with code 0
beelzebub  | time="2025-02-20T19:08:40Z" level=fatal msg="Error during ReadConfigurationsCore: : in file ./configurations/beelzebub.yaml: open ./configurations/beelzebub.yaml: no such file or directory"
beelzebub  | time="2025-02-20T19:08:40Z" level=fatal msg="Error during ReadConfigurationsCore: : in file ./configurations/beelzebub.yaml: open ./configurations/beelzebub.yaml: no such file or directory"
beelzebub exited with code 1
beelzebub  | time="2025-02-20T19:08:40Z" level=fatal msg="Error during ReadConfigurationsCore: : in file ./configurations/beelzebub.yaml: open ./configurations/beelzebub.yaml: no such file or directory"
beelzebub  | time="2025-02-20T19:08:40Z" level=fatal msg="Error during ReadConfigurationsCore: : in file ./configurations/beelzebub.yaml: open ./configurations/beelzebub.yaml: no such file or directory"
beelzebub  | time="2025-02-20T19:08:40Z" level=fatal msg="Error during ReadConfigurationsCore: : in file ./configurations/beelzebub.yaml: open ./configurations/beelzebub.yaml: no such file or directory"
beelzebub exited with code 1
beelzebub exited with code 1
beelzebub  | time="2025-02-20T19:08:40Z" level=fatal msg="Error during ReadConfigurationsCore: : in file ./configurations/beelzebub.yaml: open ./configurations/beelzebub.yaml: no such file or directory"
beelzebub  | time="2025-02-20T19:08:40Z" level=fatal msg="Error during ReadConfigurationsCore: : in file ./configurations/beelzebub.yaml: open ./configurations/beelzebub.yaml: no such file or directory"
beelzebub  | time="2025-02-20T19:08:40Z" level=fatal msg="Error during ReadConfigurationsCore: : in file ./configurations/beelzebub.yaml: open ./configurations/beelzebub.yaml: no such file or directory"
beelzebub  | time="2025-02-20T19:08:41Z" level=fatal msg="Error during ReadConfigurationsCore: : in file ./configurations/beelzebub.yaml: open ./configurations/beelzebub.yaml: no such file or directory"

```
